# Generated by Django 6.0.5 on 2026-05-31 21:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('initials', models.CharField(max_length=4)),
                ('status', models.CharField(choices=[('available', 'Available'), ('delivering', 'Delivering'), ('offline', 'Offline'), ('inactive', 'Inactive')], default='offline', max_length=20)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_location', models.CharField(blank=True, max_length=120)),
                ('location_updated_at', models.DateTimeField(blank=True, null=True)),
                ('battery_level', models.PositiveSmallIntegerField(default=100)),
                ('active_delivery_count', models.PositiveSmallIntegerField(default=0)),
                ('completion_rate', models.PositiveSmallIntegerField(default=100)),
                ('zone', models.CharField(blank=True, max_length=60)),
                ('vehicle', models.CharField(blank=True, max_length=40)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'couriers',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('initials', models.CharField(blank=True, max_length=4)),
                ('delivery_stats', models.JSONField(blank=True, default=dict)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_order_at', models.DateTimeField(blank=True, null=True)),
                ('zone', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('active', 'Active'), ('new', 'New'), ('vip', 'VIP')], default='new', max_length=20)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='PlatformPermission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'platform_permissions',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('subdomain', models.SlugField(max_length=63, unique=True)),
                ('custom_domain', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('subscription_plan', models.CharField(default='Starter', max_length=40)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('domain_settings', models.JSONField(blank=True, default=dict)),
                ('branding', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'organizations',
                'indexes': [models.Index(fields=['status'], name='organizatio_status_195db0_idx'), models.Index(fields=['subdomain'], name='organizatio_subdoma_e70a89_idx')],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=40)),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_phone', models.CharField(blank=True, max_length=40)),
                ('pickup_address', models.CharField(max_length=240)),
                ('delivery_address', models.CharField(max_length=240)),
                ('zone', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('picked_up', 'Picked up'), ('in_transit', 'In transit'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('scheduled_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='core.courier')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='core.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
            options={
                'db_table': 'deliveries',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
        ),
        migrations.CreateModel(
            name='CustomDomain',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=160, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('txt_record_name', models.CharField(max_length=160)),
                ('txt_record_value', models.CharField(max_length=160)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('ssl_status', models.CharField(default='pending', max_length=40)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
            options={
                'db_table': 'custom_domains',
            },
        ),
        migrations.AddField(
            model_name='courier',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(choices=[('platform', 'Platform'), ('organization', 'Organization'), ('api_key', 'API key'), ('system', 'System')], max_length=20)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.organization')),
            ],
            options={
                'db_table': 'audit_logs',
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('prefix', models.CharField(db_index=True, max_length=16)),
                ('key_hash', models.CharField(max_length=128, unique=True)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
            options={
                'db_table': 'api_keys',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('delivery', 'Delivery'), ('rider', 'Rider'), ('order', 'Order'), ('alert', 'Alert')], max_length=20)),
                ('message', models.CharField(max_length=200)),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('metric_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
            options={
                'db_table': 'analytics_events',
            },
        ),
        migrations.CreateModel(
            name='OrganizationPermission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
            options={
                'db_table': 'organization_permissions',
            },
        ),
        migrations.CreateModel(
            name='OrganizationRole',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=40)),
                ('label', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
                ('permissions', models.ManyToManyField(blank=True, to='core.organizationpermission')),
            ],
            options={
                'db_table': 'organization_roles',
            },
        ),
        migrations.CreateModel(
            name='OrganizationUser',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('initials', models.CharField(max_length=4)),
                ('password_hash', models.CharField(blank=True, max_length=256)),
                ('status', models.CharField(choices=[('active', 'Active'), ('invited', 'Invited'), ('suspended', 'Suspended')], default='invited', max_length=20)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.organizationrole')),
            ],
            options={
                'db_table': 'organization_users',
            },
        ),
        migrations.CreateModel(
            name='PlatformRole',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('permissions', models.ManyToManyField(blank=True, to='core.platformpermission')),
            ],
            options={
                'db_table': 'platform_roles',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='PlatformUser',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('password_hash', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.platformrole')),
            ],
            options={
                'db_table': 'platform_users',
            },
        ),
        migrations.CreateModel(
            name='ImpersonationSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('expired', 'Expired')], default='active', max_length=20)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
                ('platform_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.platformuser')),
            ],
            options={
                'db_table': 'impersonation_sessions',
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(choices=[('platform', 'Platform'), ('organization', 'Organization')], max_length=20)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=120)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('organization_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organizationuser')),
                ('platform_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.platformuser')),
                ('rotated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.refreshtoken')),
            ],
            options={
                'db_table': 'refresh_tokens',
            },
        ),
        migrations.CreateModel(
            name='TrackingLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('battery_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_logs', to='core.courier')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_logs', to='core.delivery')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
            options={
                'db_table': 'tracking_logs',
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('organization_logo', 'Organization logo'), ('proof_of_delivery', 'Proof of delivery'), ('rider_document', 'Rider document'), ('delivery_image', 'Delivery image')], max_length=40)),
                ('object_key', models.CharField(max_length=320)),
                ('original_name', models.CharField(max_length=180)),
                ('mime_type', models.CharField(max_length=120)),
                ('size_bytes', models.PositiveIntegerField()),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
            options={
                'db_table': 'uploads',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('in_app', 'In-app')], max_length=20)),
                ('event', models.CharField(max_length=80)),
                ('recipient', models.CharField(max_length=160)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
            options={
                'db_table': 'notifications',
                'indexes': [models.Index(fields=['organization', 'status'], name='notificatio_organiz_0482bb_idx'), models.Index(fields=['organization', 'event', 'created_at'], name='notificatio_organiz_45f1eb_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeliveryEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=80)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('event_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('done', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.delivery')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
            options={
                'db_table': 'delivery_events',
                'ordering': ['sort_order', 'event_at'],
                'indexes': [models.Index(fields=['organization', 'delivery'], name='delivery_ev_organiz_b05a99_idx'), models.Index(fields=['delivery', 'sort_order'], name='delivery_ev_deliver_d259b6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['organization', 'status'], name='deliveries_organiz_abc2a2_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['organization', 'courier'], name='deliveries_organiz_a99a6c_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['organization', 'scheduled_time'], name='deliveries_organiz_2e3b69_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['organization', 'created_at'], name='deliveries_organiz_456fa2_idx'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(fields=('organization', 'reference'), name='uniq_delivery_reference_per_org'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'status'], name='customers_organiz_7f9b0d_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'created_at'], name='customers_organiz_a8236f_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('organization', 'email'), name='uniq_customer_email_per_org'),
        ),
        migrations.AddIndex(
            model_name='customdomain',
            index=models.Index(fields=['organization', 'status'], name='custom_doma_organiz_a59218_idx'),
        ),
        migrations.AddIndex(
            model_name='courier',
            index=models.Index(fields=['organization', 'status'], name='couriers_organiz_052155_idx'),
        ),
        migrations.AddIndex(
            model_name='courier',
            index=models.Index(fields=['organization', 'zone'], name='couriers_organiz_d6d8f3_idx'),
        ),
        migrations.AddIndex(
            model_name='courier',
            index=models.Index(fields=['organization', 'location_updated_at'], name='couriers_organiz_517c3f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', 'created_at'], name='audit_logs_organiz_af0d8d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor_type', 'actor_id'], name='audit_logs_actor_t_3f370f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'created_at'], name='audit_logs_action_391715_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['organization', 'prefix', 'revoked_at'], name='api_keys_organiz_6f936b_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['organization', 'created_at'], name='analytics_e_organiz_b028e5_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['organization', 'type', 'created_at'], name='analytics_e_organiz_141d83_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationpermission',
            index=models.Index(fields=['organization', 'code'], name='organizatio_organiz_943093_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationpermission',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_org_permission_code'),
        ),
        migrations.AddIndex(
            model_name='organizationrole',
            index=models.Index(fields=['organization', 'key'], name='organizatio_organiz_6ac453_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationrole',
            constraint=models.UniqueConstraint(fields=('organization', 'key'), name='uniq_org_role_key'),
        ),
        migrations.AddIndex(
            model_name='organizationuser',
            index=models.Index(fields=['organization', 'status'], name='organizatio_organiz_2033aa_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationuser',
            index=models.Index(fields=['email'], name='organizatio_email_63d23a_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationuser',
            constraint=models.UniqueConstraint(fields=('organization', 'email'), name='uniq_org_user_email'),
        ),
        migrations.AddIndex(
            model_name='platformuser',
            index=models.Index(fields=['email', 'status'], name='platform_us_email_861ac6_idx'),
        ),
        migrations.AddIndex(
            model_name='impersonationsession',
            index=models.Index(fields=['organization', 'status'], name='impersonati_organiz_2dd80a_idx'),
        ),
        migrations.AddIndex(
            model_name='impersonationsession',
            index=models.Index(fields=['platform_user', 'status'], name='impersonati_platfor_ec3eea_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['subject_type', 'expires_at'], name='refresh_tok_subject_0caf62_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['organization_user', 'revoked_at'], name='refresh_tok_organiz_581547_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['platform_user', 'revoked_at'], name='refresh_tok_platfor_0a9976_idx'),
        ),
        migrations.AddIndex(
            model_name='trackinglog',
            index=models.Index(fields=['organization', 'courier', 'timestamp'], name='tracking_lo_organiz_5c679d_idx'),
        ),
        migrations.AddIndex(
            model_name='trackinglog',
            index=models.Index(fields=['organization', 'timestamp'], name='tracking_lo_organiz_58f581_idx'),
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['organization', 'type', 'created_at'], name='uploads_organiz_37bcc4_idx'),
        ),
    ]
