# Generated by Django 6.0.5 on 2026-06-04 22:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_enable_postgres_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationuser',
            name='mfa_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='mfa_secret',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='mfa_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='mfa_secret',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(choices=[('platform', 'Platform'), ('organization', 'Organization')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField(default=False)),
                ('mfa_required', models.BooleanField(default=False)),
                ('failure_reason', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.organization')),
            ],
            options={
                'db_table': 'login_attempts',
                'indexes': [models.Index(fields=['subject_type', 'email', 'created_at'], name='login_attem_subject_fc8ff9_idx'), models.Index(fields=['organization', 'created_at'], name='login_attem_organiz_adeb0b_idx'), models.Index(fields=['ip_address', 'created_at'], name='login_attem_ip_addr_f68fb5_idx'), models.Index(fields=['success', 'created_at'], name='login_attem_success_965250_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginSecurityState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(choices=[('platform', 'Platform'), ('organization', 'Organization')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('failure_count', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
            options={
                'db_table': 'login_security_states',
                'indexes': [models.Index(fields=['subject_type', 'email'], name='login_secur_subject_46a4db_idx'), models.Index(fields=['organization', 'email'], name='login_secur_organiz_023f76_idx'), models.Index(fields=['locked_until'], name='login_secur_locked__39b587_idx')],
                'constraints': [models.UniqueConstraint(fields=('subject_type', 'organization', 'email', 'ip_address'), name='uniq_login_security_identity')],
            },
        ),
    ]
