# Generated by Django 6.0.5 on 2026-06-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_organizationuser_mfa_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='impersonationsession',
            name='allowed_permissions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
