# Generated by Django 6.0.5 on 2026-06-04 22:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_impersonationsession_allowed_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationAttempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('provider', models.CharField(blank=True, max_length=80)),
                ('success', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='core.notification')),
            ],
            options={
                'db_table': 'notification_attempts',
                'indexes': [models.Index(fields=['notification', 'attempt_number'], name='notificatio_notific_1ef27a_idx'), models.Index(fields=['success', 'created_at'], name='notificatio_success_decd9d_idx')],
            },
        ),
    ]
