# Generated by Django 6.0.5 on 2026-06-04 22:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


def enable_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute('ALTER TABLE "analytics_snapshots" ENABLE ROW LEVEL SECURITY')
        cursor.execute('ALTER TABLE "analytics_snapshots" FORCE ROW LEVEL SECURITY')
        cursor.execute('DROP POLICY IF EXISTS tenant_isolation ON "analytics_snapshots"')
        cursor.execute(
            '''
            CREATE POLICY tenant_isolation ON "analytics_snapshots"
            USING (organization_id = NULLIF(current_setting('app.current_org', true), '')::uuid)
            WITH CHECK (organization_id = NULLIF(current_setting('app.current_org', true), '')::uuid)
            '''
        )


def disable_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute('DROP POLICY IF EXISTS tenant_isolation ON "analytics_snapshots"')
        cursor.execute('ALTER TABLE "analytics_snapshots" DISABLE ROW LEVEL SECURITY')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notificationattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_type', models.CharField(choices=[('daily', 'Daily')], default='daily', max_length=20)),
                ('period_start', models.DateField()),
                ('delivery_volume', models.PositiveIntegerField(default=0)),
                ('completed_deliveries', models.PositiveIntegerField(default=0)),
                ('failed_deliveries', models.PositiveIntegerField(default=0)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('average_delivery_seconds', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('delivery_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('active_courier_count', models.PositiveIntegerField(default=0)),
                ('total_courier_count', models.PositiveIntegerField(default=0)),
                ('rider_efficiency', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
            options={
                'db_table': 'analytics_snapshots',
                'indexes': [models.Index(fields=['organization', 'period_type', 'period_start'], name='analytics_s_organiz_be65ea_idx'), models.Index(fields=['organization', 'created_at'], name='analytics_s_organiz_6213cf_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'period_type', 'period_start'), name='uniq_analytics_snapshot_period')],
            },
        ),
        migrations.RunPython(enable_rls, reverse_code=disable_rls),
    ]
