# Generated by Django 6.0.5 on 2026-06-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_analyticssnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='upload',
            name='storage_url',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='uploads_organiz_337bd1_idx'),
        ),
    ]
