# Generated by Django 6.0.5 on 2026-06-04 22:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


def seed_default_branches(apps, schema_editor):
    Organization = apps.get_model("core", "Organization")
    Branch = apps.get_model("core", "Branch")
    Courier = apps.get_model("core", "Courier")
    Customer = apps.get_model("core", "Customer")
    Delivery = apps.get_model("core", "Delivery")
    OrganizationUser = apps.get_model("core", "OrganizationUser")

    for organization in Organization.objects.all():
        branch, _ = Branch.objects.get_or_create(
            organization=organization,
            code="main",
            defaults={
                "name": "Main Branch",
                "state": "Lagos",
                "city": "Lagos",
                "is_default": True,
                "status": "active",
            },
        )
        Courier.objects.filter(organization=organization, branch__isnull=True).update(branch=branch)
        Customer.objects.filter(organization=organization, branch__isnull=True).update(branch=branch)
        Delivery.objects.filter(organization=organization, branch__isnull=True).update(branch=branch)
        OrganizationUser.objects.filter(organization=organization, branch__isnull=True).exclude(role__key="owner").update(branch=branch)


def noop_reverse(apps, schema_editor):
    return None


def enable_branch_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute('ALTER TABLE "branches" ENABLE ROW LEVEL SECURITY')
        cursor.execute('ALTER TABLE "branches" FORCE ROW LEVEL SECURITY')
        cursor.execute('DROP POLICY IF EXISTS tenant_isolation ON "branches"')
        cursor.execute(
            '''
            CREATE POLICY tenant_isolation ON "branches"
            USING (organization_id = NULLIF(current_setting('app.current_org', true), '')::uuid)
            WITH CHECK (organization_id = NULLIF(current_setting('app.current_org', true), '')::uuid)
            '''
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_upload_completed_at_upload_status_upload_storage_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(max_length=40)),
                ('state', models.CharField(max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('address', models.CharField(blank=True, max_length=240)),
                ('is_default', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
            options={
                'db_table': 'branches',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='courier',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couriers', to='core.branch'),
        ),
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='core.branch'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='core.branch'),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.branch'),
        ),
        migrations.AddIndex(
            model_name='courier',
            index=models.Index(fields=['organization', 'branch'], name='couriers_organiz_46bece_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'branch'], name='customers_organiz_8bde39_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['organization', 'branch'], name='deliveries_organiz_41084c_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationuser',
            index=models.Index(fields=['organization', 'branch'], name='organizatio_organiz_514aaa_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['organization', 'status'], name='branches_organiz_30ba6c_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['organization', 'is_default'], name='branches_organiz_c9bdb3_idx'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_branch_code_per_org'),
        ),
        migrations.RunPython(seed_default_branches, reverse_code=noop_reverse),
        migrations.RunPython(enable_branch_rls, reverse_code=noop_reverse),
    ]
