# Generated by Django 6.0.5 on 2026-06-06 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_branch_courier_branch_customer_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='password_hash',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.courier'),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='subject_type',
            field=models.CharField(choices=[('platform', 'Platform'), ('organization', 'Organization'), ('courier', 'Courier')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['courier', 'revoked_at'], name='refresh_tok_courier_4dde3f_idx'),
        ),
    ]
