# Generated by Django 6.0.5 on 2026-06-06 00:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_courier_last_login_courier_password_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('dispatch', 'Dispatch'), ('courier', 'Courier')], max_length=20)),
                ('body', models.TextField()),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier_messages', to='core.branch')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.courier')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_courier_messages', to='core.organizationuser')),
            ],
            options={
                'db_table': 'courier_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['organization', 'courier', 'created_at'], name='courier_mes_organiz_b36cfe_idx'), models.Index(fields=['organization', 'branch', 'created_at'], name='courier_mes_organiz_d6f828_idx')],
            },
        ),
    ]
