# Generated by Django 6.0.5 on 2026-06-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_couriermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddIndex(
            model_name='courier',
            index=models.Index(fields=['organization', 'email'], name='couriers_organiz_fc07ac_idx'),
        ),
    ]
