# Generated by Django 6.0.5 on 2026-06-06 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_courier_email_courier_couriers_organiz_fc07ac_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='couriermessage',
            name='contact_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier_chat_messages', to='core.organizationuser'),
        ),
        migrations.AddIndex(
            model_name='couriermessage',
            index=models.Index(fields=['organization', 'courier', 'contact_user', 'created_at'], name='courier_mes_organiz_f4c737_idx'),
        ),
    ]
