# Generated by Django 6.0.5 on 2026-06-06 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_auth_users_for_platform_profiles(apps, schema_editor):
    platform_user_model = apps.get_model("core", "PlatformUser")
    auth_app_label, auth_model_name = settings.AUTH_USER_MODEL.split(".")
    user_model = apps.get_model(auth_app_label, auth_model_name)
    for profile in platform_user_model.objects.filter(user__isnull=True).exclude(email=""):
        username = profile.email
        user, created = user_model.objects.get_or_create(
            username=username,
            defaults={
                "email": profile.email,
                "first_name": (profile.name or "").split(" ", 1)[0],
                "last_name": (profile.name or "").split(" ", 1)[1] if " " in (profile.name or "") else "",
                "password": profile.password_hash or "",
                "is_staff": True,
                "is_active": profile.status == "active",
            },
        )
        if not created:
            changed = []
            if not user.email:
                user.email = profile.email
                changed.append("email")
            if profile.password_hash and not user.password:
                user.password = profile.password_hash
                changed.append("password")
            if not user.is_staff:
                user.is_staff = True
                changed.append("is_staff")
            if profile.status == "active" and not user.is_active:
                user.is_active = True
                changed.append("is_active")
            if changed:
                user.save(update_fields=changed)
        profile.user = user
        profile.save(update_fields=["user"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_couriermessage_contact_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(create_auth_users_for_platform_profiles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='auditlog',
            name='actor_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='password_hash',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
