# Generated by Django 6.0.5 on 2026-06-07 11:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_platformuser_user_alter_auditlog_actor_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicSite',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('headline', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('opening_hours', models.TextField(blank=True)),
                ('request_form_enabled', models.BooleanField(default=True)),
                ('tracking_enabled', models.BooleanField(default=True)),
                ('logo_url', models.CharField(blank=True, max_length=600)),
                ('hero_image_url', models.CharField(blank=True, max_length=600)),
            ],
            options={
                'db_table': 'public_sites',
            },
        ),
        migrations.CreateModel(
            name='PublicSiteServiceArea',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'public_site_service_areas',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='external_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='delivery',
            name='source',
            field=models.CharField(default='dashboard', max_length=80),
        ),
        migrations.AddField(
            model_name='delivery',
            name='source_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('pending', 'Pending'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('picked_up', 'Picked up'), ('in_transit', 'In transit'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['organization', 'source'], name='deliveries_organiz_1501a2_idx'),
        ),
        migrations.AddField(
            model_name='publicsite',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_site', to='core.organization'),
        ),
        migrations.AddField(
            model_name='publicsiteservicearea',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
        ),
        migrations.AddField(
            model_name='publicsiteservicearea',
            name='public_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='core.publicsite'),
        ),
        migrations.AddIndex(
            model_name='publicsite',
            index=models.Index(fields=['organization', 'enabled'], name='public_site_organiz_e38b58_idx'),
        ),
        migrations.AddConstraint(
            model_name='publicsite',
            constraint=models.UniqueConstraint(fields=('organization',), name='uniq_public_site_per_org'),
        ),
        migrations.AddIndex(
            model_name='publicsiteservicearea',
            index=models.Index(fields=['organization', 'public_site', 'sort_order'], name='public_site_organiz_37892e_idx'),
        ),
        migrations.AddConstraint(
            model_name='publicsiteservicearea',
            constraint=models.UniqueConstraint(fields=('public_site', 'name'), name='uniq_public_site_service_area_name'),
        ),
    ]
