# Generated by Django 6.0.5 on 2026-06-07 12:08

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_publicsite_publicsiteservicearea_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicSitePage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.CharField(default='/', max_length=180, validators=[core.models.validate_public_site_slug])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('meta_title', models.CharField(blank=True, max_length=180)),
                ('meta_description', models.CharField(blank=True, max_length=240)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
                ('public_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.publicsite')),
            ],
            options={
                'db_table': 'public_site_pages',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PublicSiteBlock',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('hero', 'Hero'), ('rich_text', 'Rich text'), ('service_areas', 'Service areas'), ('request_cta', 'Request CTA'), ('contact_band', 'Contact band'), ('faq', 'FAQ')], max_length=40)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('eyebrow', models.CharField(blank=True, max_length=80)),
                ('headline', models.CharField(blank=True, max_length=180)),
                ('body', models.TextField(blank=True)),
                ('button_label', models.CharField(blank=True, max_length=80)),
                ('button_href', models.CharField(blank=True, max_length=180)),
                ('image_url', models.CharField(blank=True, max_length=600)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
                ('public_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.publicsite')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.publicsitepage')),
            ],
            options={
                'db_table': 'public_site_blocks',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='publicsitepage',
            index=models.Index(fields=['organization', 'public_site', 'status'], name='public_site_organiz_ed146d_idx'),
        ),
        migrations.AddIndex(
            model_name='publicsitepage',
            index=models.Index(fields=['organization', 'public_site', 'slug'], name='public_site_organiz_49dec4_idx'),
        ),
        migrations.AddConstraint(
            model_name='publicsitepage',
            constraint=models.UniqueConstraint(fields=('public_site', 'slug'), name='uniq_public_site_page_slug'),
        ),
        migrations.AddIndex(
            model_name='publicsiteblock',
            index=models.Index(fields=['organization', 'public_site', 'page', 'sort_order'], name='public_site_organiz_849ad0_idx'),
        ),
        migrations.AddIndex(
            model_name='publicsiteblock',
            index=models.Index(fields=['organization', 'type'], name='public_site_organiz_c97e8b_idx'),
        ),
    ]
